# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
  lib,
  fetchurl,
  installShellFiles,
  stdenvNoCC,
}:
let
  inherit (stdenvNoCC.hostPlatform) system;
  shaMap = {
    x86_64-linux = "11bgiklcg58nlmrfcl0lfpip1r936jc9h0s6ybzc8nn7axyqmjzn";
    x86_64-darwin = "0mx6izadzmc35mlm39m8y8fi6qlg9ln76k8hv620029h0ad0v3ka";
  };

  urlMap = {
    x86_64-linux = "https://github.com/atomicptr/peon/releases/download/v0.2.0/peon_0.2.0_linux_amd64.tar.gz";
    x86_64-darwin = "https://github.com/atomicptr/peon/releases/download/v0.2.0/peon_0.2.0_darwin_amd64.tar.gz";
  };
in
stdenvNoCC.mkDerivation {
  pname = "peon";
  version = "0.2.0";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = ".";

  nativeBuildInputs = [ installShellFiles ];

  installPhase = ''
    runHook preInstall
    mkdir -p $out/bin
    cp -vr ./peon $out/bin/peon
    runHook postInstall
  '';

  meta = {
    description = "Peon is a simple Git Worktree management tool designed for humans";
    homepage = "https://github.com/atomicptr/peon";
    license = lib.licenses.gpl3;

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
