# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
  lib,
  fetchurl,
  installShellFiles,
  stdenvNoCC,
}:
let
  inherit (stdenvNoCC.hostPlatform) system;
  shaMap = {
    x86_64-linux = "1nmn0kd9xlrvkgqy14rr651cjn5rjjjqqhj7p3f4jqdxwvrrjdk4";
    x86_64-darwin = "0xdvn0j1yjiy1wam4dx3vcpzf32n5l1601zmkwywn5a0fwv41mk0";
  };

  urlMap = {
    x86_64-linux = "https://github.com/atomicptr/peon/releases/download/v0.3.0/peon_0.3.0_linux_amd64.tar.gz";
    x86_64-darwin = "https://github.com/atomicptr/peon/releases/download/v0.3.0/peon_0.3.0_darwin_amd64.tar.gz";
  };
in
stdenvNoCC.mkDerivation {
  pname = "peon";
  version = "0.3.0";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = ".";

  nativeBuildInputs = [ installShellFiles ];

  installPhase = ''
    runHook preInstall
    mkdir -p $out/bin
    cp -vr ./peon $out/bin/peon
    runHook postInstall
  '';

  meta = {
    description = "Peon is a simple Git Worktree management tool designed for humans";
    homepage = "https://github.com/atomicptr/peon";
    license = lib.licenses.gpl3;

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
