# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
  lib,
  fetchurl,
  installShellFiles,
  stdenvNoCC,
}:
let
  inherit (stdenvNoCC.hostPlatform) system;
  shaMap = {
    x86_64-linux = "0n7iz4zfw8wh9psyvw44j5agxmwqffxxw7d7z052f92sjgbv05kr";
    x86_64-darwin = "0sp103wlpc1qc16wc05gwg0x1qg5gij0f83j9bydp6js2w1qcin0";
  };

  urlMap = {
    x86_64-linux = "https://github.com/atomicptr/peon/releases/download/v0.1.0/peon_0.1.0_linux_amd64.tar.gz";
    x86_64-darwin = "https://github.com/atomicptr/peon/releases/download/v0.1.0/peon_0.1.0_darwin_amd64.tar.gz";
  };
in
stdenvNoCC.mkDerivation {
  pname = "peon";
  version = "0.1.0";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = ".";

  nativeBuildInputs = [ installShellFiles ];

  installPhase = ''
    runHook preInstall
    mkdir -p $out/bin
    cp -vr ./peon $out/bin/peon
    runHook postInstall
  '';

  meta = {
    description = "Peon is a simple Git Worktree management tool designed for humans";
    homepage = "https://github.com/atomicptr/peon";
    license = lib.licenses.gpl3;

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
