# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
system ? builtins.currentSystem
, lib
, fetchurl
, installShellFiles
, stdenvNoCC
}:
let
  shaMap = {
    x86_64-linux = "18c2mxaf0f01c1905c7ppnq9cq07qr4nn5al9zn9idhzk9b8mf9q";
    x86_64-darwin = "10w9xv7z8fw4628pwnw9dj2n3wf3g0lgfcpy3k2f3v6fhv30abwm";
  };

  urlMap = {
    x86_64-linux = "https://github.com/atomicptr/crab/releases/download/v1.4.4/crab_1.4.4_linux_amd64.tar.gz";
    x86_64-darwin = "https://github.com/atomicptr/crab/releases/download/v1.4.4/crab_1.4.4_darwin_amd64.tar.gz";
  };
in
stdenvNoCC.mkDerivation {
  pname = "crab";
  version = "1.4.4";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = ".";

  nativeBuildInputs = [ installShellFiles ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr ./crab $out/bin/crab
  '';

  system = system;

  meta = {
    description = "A versatile tool to crawl dozens of URLs from a given source, like a sitemap or an URL list.
";
    homepage = "https://github.com/atomicptr/crab";
    license = lib.licenses.mit;

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
