# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
  lib,
  fetchurl,
  installShellFiles,
  stdenvNoCC,
}:
let
  inherit (stdenvNoCC.hostPlatform) system;
  shaMap = {
    x86_64-linux = "0z8fszw4kz6s2nnx896fhjnz5z4ifgg8qrdklfpbzgqya2rbdzx5";
    x86_64-darwin = "1cjkgiyliiffaamybvsy8bfzgbg4wa7dvbm3hiwn738d3b89az6a";
  };

  urlMap = {
    x86_64-linux = "https://github.com/atomicptr/crab/releases/download/v1.5.0/crab_1.5.0_linux_amd64.tar.gz";
    x86_64-darwin = "https://github.com/atomicptr/crab/releases/download/v1.5.0/crab_1.5.0_darwin_amd64.tar.gz";
  };
in
stdenvNoCC.mkDerivation {
  pname = "crab";
  version = "1.5.0";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = ".";

  nativeBuildInputs = [ installShellFiles ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr ./crab $out/bin/crab
  '';

  meta = {
    description = "A versatile tool to crawl dozens of URLs from a given source, like a sitemap or an URL list.
";
    homepage = "https://github.com/atomicptr/crab";
    license = lib.licenses.mit;

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
