# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
system ? builtins.currentSystem
, lib
, fetchurl
, installShellFiles
, stdenvNoCC
}:
let
  shaMap = {
    x86_64-linux = "167wx15xqjisq0q5p4fa69jxcmqrqlndd6992rndwwxzb26k1a6s";
    x86_64-darwin = "04acb9rbwhzipgx0q7pncybn1wx5liy83n1m0slg6cxg6zcwm0dy";
  };

  urlMap = {
    x86_64-linux = "https://github.com/atomicptr/tmplr/releases/download/v0.3.1/tmplr_0.3.1_linux_amd64.tar.gz";
    x86_64-darwin = "https://github.com/atomicptr/tmplr/releases/download/v0.3.1/tmplr_0.3.1_darwin_amd64.tar.gz";
  };
in
stdenvNoCC.mkDerivation {
  pname = "tmplr";
  version = "0.3.1";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = ".";

  nativeBuildInputs = [ installShellFiles ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr ./tmplr $out/bin/tmplr
  '';

  system = system;

  meta = {
    description = "Quickly create new files from templates
";
    homepage = "https://github.com/atomicptr/tmplr";
    license = lib.licenses.gpl3;

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
