# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
system ? builtins.currentSystem
, lib
, fetchurl
, installShellFiles
, stdenvNoCC
}:
let
  shaMap = {
    x86_64-linux = "11kdn306sk72csx6cqqa4vzq7fimpmbqd3x74lywl1r6w73x823p";
    x86_64-darwin = "0sni6avk6nl6260bs0pdcfqyvf4gvaiw887gmcqnk7jsi87rsamb";
  };

  urlMap = {
    x86_64-linux = "https://github.com/atomicptr/tmplr/releases/download/v0.2.2/tmplr_0.2.2_linux_amd64.tar.gz";
    x86_64-darwin = "https://github.com/atomicptr/tmplr/releases/download/v0.2.2/tmplr_0.2.2_darwin_amd64.tar.gz";
  };
in
stdenvNoCC.mkDerivation {
  pname = "tmplr";
  version = "0.2.2";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = ".";

  nativeBuildInputs = [ installShellFiles ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr ./tmplr $out/bin/tmplr
  '';

  system = system;

  meta = {
    description = "Quickly create new files from templates
";
    homepage = "https://github.com/atomicptr/tmplr";
    license = lib.licenses.gpl3;

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
