# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
  system ? builtins.currentSystem,
  lib,
  fetchurl,
  installShellFiles,
  stdenvNoCC,
}:
let
  shaMap = {
    x86_64-linux = "0v2x75bnfg6fnin9lhwml2zgyjhgczixgsga37y53ays2w9h7b7s";
    x86_64-darwin = "1rag8qrjds6y49ac34bjs83ivbbf9rmw17pdl1dc9cwnc7j1p0f6";
  };

  urlMap = {
    x86_64-linux = "https://github.com/atomicptr/tmplr/releases/download/v0.3.2/tmplr_0.3.2_linux_amd64.tar.gz";
    x86_64-darwin = "https://github.com/atomicptr/tmplr/releases/download/v0.3.2/tmplr_0.3.2_darwin_amd64.tar.gz";
  };
in
stdenvNoCC.mkDerivation {
  pname = "tmplr";
  version = "0.3.2";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = ".";

  nativeBuildInputs = [ installShellFiles ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr ./tmplr $out/bin/tmplr
  '';

  system = system;

  meta = {
    description = "Quickly create new files from templates
";
    homepage = "https://github.com/atomicptr/tmplr";
    license = lib.licenses.gpl3;

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
